name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  APP_VERSION: v1.0.${{ github.run_number }}

jobs:
  build:
    name: Build & Deploy
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ env.APP_VERSION }}
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_PUBLIC_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e
            if [ ! -d "/root/ops-basic-spring-ec2-back" ]; then
              git clone git@github.com:shlomi-sharbet/ops-basic-spring-ec2-back.git /root/ops-basic-spring-ec2-back
            fi
            cd /root/ops-basic-spring-ec2-back
            git checkout -- .
            git pull origin master
            /usr/local/bin/docker-compose  down || true
            sed -i 's/image: ${{ secrets.DOCKERHUB_USERNAME }}\/backend:.*/image: ${{ secrets.DOCKERHUB_USERNAME }}\/backend:v1.0.${{ github.run_number }}/g' /root/ops-basic-spring-ec2-back/docker-compose.yml
            /usr/local/bin/docker-compose  up -d || true